name: Update README on Release

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Щоб git log працював повноцінно

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Generate README from release
        run: python .github/scripts/generate_readme.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push changes
        run: |
          git config user.name "readme-bot"
          git config user.email "bot@example.com"
          git add README.md
          git diff --cached --quiet || git commit -m "auto: update README for ${{ github.event.release.tag_name }}"
          git push
